Update linter

diff --git a/.github/workflows/scipt-linter.yaml b/.github/workflows/scipt-linter.yaml
--- a/.github/workflows/scipt-linter.yaml
+++ b/.github/workflows/scipt-linter.yaml
@@ -25,9 +25,9 @@ jobs:
     #   run: |
     #     find . -type f -name "*.sh" -exec shellcheck {} \;
   
-    - name: Check for Errors
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Linting failed. There are errors in the Bash scripts."
-          exit 1
-        fi
+    # - name: Check for Errors
+    #   run: |
+    #     if [ $? -ne 0 ]; then
+    #       echo "Linting failed. There are errors in the Bash scripts."
+    #       exit 1
+    #     fi
